CREATE TABLE IF NOT EXISTS users(
    id uuid PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email_address TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    password TEXT NOT NULL
);